<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>goatty</AssemblyName>
    <RootNamespace>Goatty</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="[12.1.1]" />
    <PackageReference Include="Avalonia.Desktop" Version="[12.1.1]" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="[12.1.1]" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="[12.1.1]" />
    <PackageReference Include="Avalonia.Wayland" Version="[12.1.1]" />
    <PackageReference Include="Iciclecreek.Avalonia.Terminal" Version="[3.1.0]" />
  </ItemGroup>
</Project>
